### ISSUE TITLE
The `add-path` command is deprecated and will be disabled on November 16th.

### ISSUE THREAD

**Issue by sergey19941201** [Malcolmnixon/Setup-VSTest#10]
Getting error that command will be disabled on November 16th.

```
   - name: Setup VSTest.exe
      uses: Malcolmnixon/Setup-VSTest@v3

    - name: VSTest
      run:        
          vstest.console MyApp.UnitTests.Droid.dll
```
